apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: preview-server
  region: us-west-2

vpc:
  subnets:
    private:
      us-west-2a: { id: subnet-0ad66057 }
      us-west-2b: { id: subnet-9a3e10b1 }
      us-west-2c: { id: subnet-d050f4a8 }
      us-west-2d: { id: subnet-d2d91898 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true